### ISSUE TITLE
`osbuild-composer` should allow arbitrary locations for custom files

### ISSUE THREAD

**Issue by supakeen** [osbuild/fedora-blueprints#2]
The `kde-live.toml` blueprint needs to create a directory in `/root` and configure the window manager there (theme-wise). Currently `osbuild-composer` disallows this.

**Comment by teg** [comment]
An option is to add `/root` to the allow list, and in that way still make sure `/usr` and friends is owned by `rpm`.

**Comment by supakeen** [comment]
> An option is to add `/root` to the allow list, and in that way still make sure `/usr` and friends is owned by `rpm`.

These are the locations that current kickstarts write to, while some of these might be redundant a lot of them write to `/usr/share`.
- `/usr`
- `/home`
- `/etc`
- `/tmp`
- `/boot`

**Comment by teg** [comment]
I think it would be much more appealing if we could accomplish the fedora spins with features we would at least in principle be happy to add to RHEL.

We could open up the file writing more, but requiring things to be packaged in rpms could also be a fine outcome, we don't need to replicate the kickstarts precisely as long as the same result is achievable.

If we do open things up more we should at the very least ensure we only allow writing to locations that work with both ostree and non-ostree image types.

**Comment by teg** [comment]
To expand on the Fedora only approach: if fedora requires things that are a no-go in RHEL we are stuck in two universes and can't move things from fedora to RHEL. Might be ok, but would be a real shame.

I think we should strive to find solutions that would be acceptable everywhere, even if that means reconsidering what we find acceptable.

**Comment by supakeen** [comment]
> I think it would be much more appealing if we could accomplish the fedora spins with features we would at least in principle be happy to add to RHEL.
> 
> We could open up the file writing more, but requiring things to be packaged in rpms could also be a fine outcome, we don't need to replicate the kickstarts precisely as long as the same result is achievable.
> 
> If we do open things up more we should at the very least ensure we only allow writing to locations that work with both ostree and non-ostree image types.

For ostree we can write everywhere while building a commit; we can't write everywhere while deploying a commit. 

While putting stuff in RPMs works well for spin maintainers it works much less well for people that want to experiment with building a new spin or their own customized desktop.

I agree that it's hard to reconcile not-allowed-to-break-RHEL with build-your-own-distro-with-fedora-packages perhaps there *is* a way to have both and benefit both. I *think* that alternative would be to implement stages (and corresponding customizations) for the common locations that are being written to.

**Comment by ondrejbudai** [comment]
My quick 5 cents: I think we should definitely allow people to put custom files into `/home/*/`. The goal of the customization is to allow people to **configure** packages inside the image, and many packages store their configs under the home directory. And since `/root` is just a home for `root`, we can add it as well.

I still need to be convinced about other directories, but these currently seem like a no-brainer to me.

**Comment by Conan-Kudo** [comment]
For what it's worth, I'm okay with an outcome of this that we get more of this stuff "packaged". I went through and created `livesys-scripts` because there was no way to transpose that logic into kiwi or osbuild, and I needed that stuff for working live media.

Many of these kickstarts haven't been thoroughly examined in a very long time.

**Comment by supakeen** [comment]
During todays team meeting we decided to start by widening this with `/root` which is needed by the KDE spin and to then wait for a new usecase to see if we want to widen it more (a lot of spins write into `/usr`). I'll be submitting a PR for that shortly.
